version: '3'

services:
  client:
    build: ./receiver
    command: receiver.js
    stdin_open: true
    ports:
      - 8080
    volumes:
      - ./client:/var/www

  server:
    build: ./sender
    command: sender.js
    ports:
      - 8080