version: '3'

services:
  receiver:
    build: .
    command: receiver.js
    stdin_open: true
    ports:
      - 8080
    volumes:
      - ./client:/var/www

  sender:
    build: .
    command: sender.js
    stdin_open: true
    ports:
      - 8080