version: '3'

services:
  client:
    build: ./client
    # command: tcp
    stdin_open: true
    ports:
      - 10000
    volumes:
      - ./client:/var/www

  server:
    build: ./client
    # command: tcp
    ports:
      - 10000
    volumes:
      - ./server:/var/www

  tictactoe:
    build: ./tictactoe